import Sidebar from "@/components/sidebar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />
            <main className="flex-1 p-4 bg-gray-100">{children}</main>
        </div>
      </body>
    </html>
  );
}
